use     dk_db_apps
go

drop    INDEX [DK_TBL_FXSA_TRADES_1] on DK_TBL_FXSA_TRADES
drop    INDEX [DK_TBL_FXSA_TRADES_2] on DK_TBL_FXSA_TRADES
drop    INDEX [DK_TBL_FXSA_TRADES_3] on DK_TBL_FXSA_TRADES
drop    INDEX [DK_TBL_FXSA_TRADES_4] on DK_TBL_FXSA_TRADES
drop    INDEX [DK_TBL_FXSA_TRADES_5] on DK_TBL_FXSA_TRADES
go

create  index DK_TBL_FXSA_TRADES_DK_TFT_BROKER
ON      [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_BROKER],[DK_TFT_TRANS_TYPE],[DK_TFT_STATUS])
INCLUDE ([DK_TFT_TRADE_NO],[DK_TFT_DENOM_AMT], DK_TFT_BATCH_ID)
with    (data_compression = page, fillfactor = 80)

CREATE  INDEX [DK_TBL_FXSA_TRADES_DK_TFT_STATUS]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_STATUS])
INCLUDE ([DK_TFT_TRADE_NO],[DK_TFT_TRANS_TYPE],[DK_TFT_DENOM_AMT],[DK_TFT_DENOM_JPY_ORIGINAL_AMT])
with    (data_compression = page, fillfactor = 80)

CREATE INDEX [DK_TBL_FXSA_TRADES_DK_TFT_LOCAL_CCY]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_LOCAL_CCY],[DK_TFT_TRADE_NO],[DK_TFT_STATUS])
with    (data_compression = page, fillfactor = 80)

CREATE  INDEX DK_TBL_FXSA_TRADES_DK_TFT_ULT_ACCOUNT_NO_DK_TFT_BATCH_ID
ON      DK_TBL_FXSA_TRADES ( [DK_TFT_ULT_ACCOUNT_NO], [DK_TFT_BATCH_ID],[DK_TFT_ACCOUNT_NO], [DK_TFT_MANAGER_CODE] )
with    (data_compression = page, fillfactor = 80)