CREATE NONCLUSTERED INDEX [DK_TBL_FXF_SPOT_1]
ON [dbo].[DK_TBL_FXF_SPOT] ([DK_TFS_STATUS])
INCLUDE ([DK_TFS_ID],[DK_TFS_TKT],[DK_TFS_EXTRACT_ID])


CREATE NONCLUSTERED INDEX [DK_TBL_FXF_SPOT_2]
ON [dbo].[DK_TBL_FXF_SPOT] ([DK_TFS_EXTRACT_ID],[DK_TFS_STATUS],[DK_TFS_IS_SENT])
INCLUDE ([DK_TFS_CUST_ACCT])

CREATE NONCLUSTERED INDEX [DK_TBL_FXF_SPOT_3]
ON [dbo].[DK_TBL_FXF_SPOT] ([DK_TFS_EXTRACT_ID],[DK_TFS_CUST_ACCT],[DK_TFS_IS_SENT])
INCLUDE ([DK_TFS_TKT],[DK_TFS_PORTFOLIO],[DK_TFS_RECORD_ID],[DK_TFS_TRADE_NO],[DK_TFS_TRADE_TYPE],[DK_TFS_TRADE_TYPE2],[DK_TFS_T_DATE],[DK_TFS_TRADE_TIME],[DK_TFS_SETTLE_DATE],[DK_TFS_ACCOUNT_NO],[DK_TFS_CCY],[DK_TFS_SETTLE_CCY],[DK_TFS_DENOM_CCY],[DK_TFS_TXN_TYPE],[DK_TFS_DENOM_AMT],[DK_TFS_PRICE],[DK_TFS_TRADE_AMT],[DK_TFS_ALLOC_AMT],[DK_TFS_UNALLOC_AMT],[DK_TFS_NOTES],[DK_TFS_CREATE_USER],[DK_TFS_CREATE_DATETIME],[DK_TFS_UPDATE_USER],[DK_TFS_UPDATE_DATETIME],[DK_TFS_STATUS],[DK_TFS_ULT_ACCOUNT_NO],[DK_TFS_IS_DELTA_TRADE],[DK_TFS_GENEVA_MANAGER_CODE],[DK_TFS_TRADE_ID],[DK_TFS_DEAL_DESC])

CREATE NONCLUSTERED INDEX [DK_TBL_FXF_SPOT_4]
ON [dbo].[DK_TBL_FXF_SPOT] ([DK_TFS_EXTRACT_ID],[DK_TFS_CUST_ACCT],[DK_TFS_IS_SENT])
INCLUDE ([DK_TFS_TKT],[DK_TFS_PORTFOLIO],[DK_TFS_TRADE_NO],[DK_TFS_T_DATE],[DK_TFS_SETTLE_DATE],[DK_TFS_ACCOUNT_NO],[DK_TFS_CCY],[DK_TFS_SETTLE_CCY],[DK_TFS_TXN_TYPE],[DK_TFS_DENOM_AMT],[DK_TFS_NET_SETTLE_AMT],[DK_TFS_PRICE],[DK_TFS_FX_RATE],[DK_TFS_TRANS_INSTR],[DK_TFS_TRADE_AMT],[DK_TFS_ALLOC_AMT],[DK_TFS_UNALLOC_AMT],[DK_TFS_NOTES],[DK_TFS_COMMISSION],[DK_TFS_FEES],[DK_TFS_CPTY],[DK_TFS_CREATE_USER],[DK_TFS_CREATE_DATETIME],[DK_TFS_UPDATE_USER],[DK_TFS_UPDATE_DATETIME],[DK_TFS_STATUS],[DK_TFS_ULT_ACCOUNT_NO],[DK_TFS_IS_DELTA_TRADE],[DK_TFS_GENEVA_MANAGER_CODE],[DK_TFS_TRADE_ID],[DK_TFS_DEAL_DESC])

CREATE NONCLUSTERED INDEX [DK_TBL_FXSA_TRADES_1]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_BROKER],[DK_TFT_TRANS_TYPE],[DK_TFT_STATUS])
INCLUDE ([DK_TFT_TRADE_NO],[DK_TFT_DENOM_AMT])

CREATE NONCLUSTERED INDEX [DK_TBL_FXSA_TRADES_2]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_BROKER],[DK_TFT_TRANS_TYPE],[DK_TFT_STATUS])
INCLUDE ([DK_TFT_ID],[DK_TFT_TRADE_NO])

CREATE NONCLUSTERED INDEX [DK_TBL_FXSA_TRADES_3]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_STATUS])
INCLUDE ([DK_TFT_TRADE_NO],[DK_TFT_TRANS_TYPE],[DK_TFT_DENOM_AMT],[DK_TFT_DENOM_JPY_ORIGINAL_AMT])


CREATE NONCLUSTERED INDEX [DK_TBL_FXSA_TRADES_4]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_LOCAL_CCY],[DK_TFT_TRADE_NO],[DK_TFT_STATUS])
INCLUDE ([DK_TFT_ID])

CREATE NONCLUSTERED INDEX [DK_TBL_FXSA_TRADES_5]
ON [dbo].[DK_TBL_FXSA_TRADES] ([DK_TFT_BROKER],[DK_TFT_TRANS_TYPE],[DK_TFT_STATUS])
INCLUDE ([DK_TFT_ID],[DK_TFT_TRADE_NO],[DK_TFT_BATCH_ID])
